In [104]:
import pandas as pd
import numpy as np

In [105]:
df=pd.read_csv(r"D:\Data Science\Notes\titanic\train.csv")

In [106]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [107]:
df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1,inplace=True)

In [108]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [109]:
x=df.iloc[:,1:]
y=df.iloc[:,0]

In [110]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [111]:
y_train.head()

662    0
370    1
768    0
799    0
600    1
Name: Survived, dtype: int64

In [112]:
from sklearn.impute import SimpleImputer

In [113]:
si_age=SimpleImputer()
si_embark=SimpleImputer(strategy='most_frequent')

x_train_age=si_age.fit_transform(x_train[['Age']])
x_train_embark=si_embark.fit_transform(x_train[['Embarked']])

x_test_age=si_age.transform(x_test[['Age']])
x_test_embark=si_embark.transform(x_test[['Embarked']])

In [114]:
from sklearn.preprocessing import OneHotEncoder
ohe_sex=OneHotEncoder(sparse=False,handle_unknown='ignore')
ohe_embark = OneHotEncoder(sparse=False,handle_unknown='ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embark = ohe_embark.fit_transform(x_train_embark)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embark = ohe_embark.transform(x_test_embark)

In [115]:
x_train_embark

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [116]:
x_train_rem=x_train.drop(['Age','Embarked','Sex'],axis=1)

In [117]:
x_test_rem=x_test.drop(['Age','Embarked','Sex'],axis=1)

In [118]:
x_train_transformed=np.concatenate((x_train_rem,x_train_embark,x_train_age,x_train_sex),axis=1)

In [119]:
x_test_transformed=np.concatenate((x_test_rem,x_test_embark,x_test_age,x_test_sex),axis=1)

In [120]:
x_test_transformed.shape

(179, 10)

In [121]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [122]:
y_pred = clf.predict(x_test_transformed)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [123]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7821229050279329

In [124]:
import pickle

In [125]:
pickle.dump(ohe_sex,open('Models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embark,open('Models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('Models/clf.pkl','wb'))

## predicting using models

In [126]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embark= pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [127]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [128]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\yoges\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [129]:
test_input_embark= ohe_embark.transform(test_input[:,-1].reshape(1,1))

In [130]:
test_input_age = test_input[:,2].reshape(1,1)

In [132]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embark),axis=1)

In [133]:
test_input_transformed.shape

(1, 10)

In [134]:
clf.predict(test_input_transformed)

array([1], dtype=int64)